[package]
name = "tree_gen_derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0" }
quote = "1.0"
proc-macro2 = "1.0"
tree_gen = { version = "0.1.0", path = "../tree_gen" }
